# A workflow that uses standard platform-dependent compilation paths etc
# and then builds with pip / setup.py on top of that.

name: pip builds 

on: 
  push:
    
  pull_request:
      
  workflow_dispatch:

jobs:
  build_with_pip:
    name: ${{matrix.os}} build with pip (${{ matrix.python-version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest']
        python-version: ['2.7', '3.7', '3.8']
        exclude:
          - os: 'windows-latest'
            python-version: 2.7
          - os: 'windows-latest'
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout  
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
            
          key: macos-test-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_test_environment.yml') }}

      - name: Miniconda + Cache
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: "latest"
            auto-update-conda: true
            environment-file: .github/workflows/resources/conda_test_environment.yml
            activate-environment: conda-test
            python-version: 3.7
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
  
      - name: Install (self)
        shell: bash -l {0}
        run: |
          cd miller_alaskamoho_srl2018-src
          pip install -e .      

      - name: Test 
        shell: bash -l {0}
        run: |
          python -c 'import miller_alaskamoho_srl2018 as alaskamoho;'
          # Haven't written these yet !
          # pip install pytest
          # pytest
 
     